# Generated by Django 5.0 on 2023-12-23 08:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('titile', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('bookshelf', models.CharField(choices=[('main', 'Main'), ('second', 'Second'), ('third', 'Third')], max_length=100)),
                ('shelf', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
