# Generated by Django 5.0 on 2023-12-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_titile_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookshelf',
            field=models.CharField(choices=[('main', 'Шкаф №1'), ('second', 'Шкаф №2'), ('third', 'Полки')], max_length=100),
        ),
    ]
