# Generated by Django 5.0 on 2023-12-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_bookshelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookshelf',
            field=models.CharField(choices=[('main', 'Шкаф №1'), ('second', 'Шкаф №2'), ('third', 'Полки')], max_length=100),
        ),
    ]
