# Generated by Django 5.0 on 2023-12-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='placement',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
