# Generated by Django 5.0 on 2023-12-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='placement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
